// <auto-generated />
using System;
using ConsoleCars.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConsoleCars.API.Migrations
{
    [DbContext(typeof(VeiculoContext))]
    [Migration("20260206195503_CriandoTabelaVeiculos")]
    partial class CriandoTabelaVeiculos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConsoleCars.Lib.Modelos.Veiculo", b =>
                {
                    b.Property<string>("Placa")
                        .HasColumnType("text");

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<string>("Atualizacao")
                        .HasColumnType("text");

                    b.Property<int>("Cambio")
                        .HasColumnType("integer");

                    b.Property<int>("Carroceria")
                        .HasColumnType("integer");

                    b.Property<int>("Combustivel")
                        .HasColumnType("integer");

                    b.Property<int>("Cor")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataVenda")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoAnuncio")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrecoCompra")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PrecoVenda")
                        .HasColumnType("numeric");

                    b.Property<int>("Quilometragem")
                        .HasColumnType("integer");

                    b.HasKey("Placa");

                    b.ToTable("Veiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
